#!/usr/bin/env python3
"""Package skills as individual .zip files for upload to claude.ai chat.

claude.ai chat does not install Claude Code plugins. It takes ONE ZIP PER SKILL, under
Settings -> Capabilities -> Upload skill, and each uploaded skill is off by default until
you enable it from the Skills menu in a conversation.

So the plugin is the right unit for Claude Code (CLI, desktop, claude.ai/code) and the
wrong unit for chat. This produces the chat unit from the same source, so there is still
only one place these skills are authored.

CLI-only skills are skipped: they need a checkout, git, or local hooks, and uploading them
to chat produces a skill that cannot do its job. Pass --all to override.

    python3 scripts/package-for-chat.py           # the skills that work in chat
    python3 scripts/package-for-chat.py --all     # every skill, CLI-only included
"""

from __future__ import annotations

import argparse
import pathlib
import shutil
import sys
import zipfile

PLUGIN = pathlib.Path(__file__).resolve().parent.parent
DIST = PLUGIN / "dist" / "chat-skills"

# claude.ai's published guidance for a skill's full content. Not a hard limit, but a skill
# well past it crowds the conversation it is meant to help.
TOKEN_GUIDANCE = 5000


def est_tokens(chars: int) -> int:
    return chars // 4


def first_sentence(skill_md: str) -> str:
    """The description's first sentence, which is what a chooser actually reads."""
    for line in skill_md.splitlines():
        if line.startswith("description:"):
            d = line.split(":", 1)[1].strip().removeprefix("[CLI-only]").strip()
            return d.split(". ")[0].rstrip(".")
    return ""


def write_index(rows: list[tuple[str, int, int, str]]) -> None:
    """An upload list, because claude.ai takes one zip at a time and 38 of them is a chore
    without an order to work through."""
    lines = [
        "# Upload list for claude.ai chat",
        "",
        "claude.ai chat does not install plugins. Upload these one at a time:",
        "**Settings -> Capabilities -> Upload skill**, then enable each one from the Skills",
        "menu inside a conversation. They are off by default.",
        "",
        "Requires Pro, Max, Team or Enterprise with code execution enabled.",
        "",
        "`tokens` is SKILL.md, which enters the conversation. `bundled` sits on disk and is",
        "read on demand by code execution, so it costs nothing until it is used.",
        "",
        "| Skill | tokens | bundled | What it does |",
        "|---|---|---|---|",
    ]
    for name, tokens, kb, desc in sorted(rows):
        lines.append(f"| `{name}` | {tokens} | {str(kb) + 'KB' if kb else ''} | {desc} |")
    lines += ["", f"{len(rows)} skills. Generated by `scripts/package-for-chat.py`."]
    (DIST / "INDEX.md").write_text("\n".join(lines) + "\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--all", action="store_true", help="include CLI-only skills")
    ap.add_argument("--root", action="append", default=[], metavar="DIR",
                    help="an extra skills/ directory to package alongside this plugin's. "
                         "Repeatable. Lets a dependent plugin build one complete upload set "
                         "without holding a copy of this script.")
    ap.add_argument("--out", metavar="DIR",
                    help="where to write the zips (default: this plugin's dist/chat-skills)")
    args = ap.parse_args()

    global DIST
    if args.out:
        DIST = pathlib.Path(args.out).expanduser().resolve()

    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir(parents=True)

    roots = [PLUGIN / "skills"]
    for extra in args.root:
        d = pathlib.Path(extra).expanduser().resolve()
        if d.is_dir():
            roots.append(d)
            print(f"also packaging {d}")
        else:
            print(f"--root {extra} is not a directory; ignored", file=sys.stderr)
    if args.root:
        print()

    packaged, skipped, fat, rows = 0, [], [], []
    for skill_dir in sorted((d for r in roots for d in r.iterdir()), key=lambda d: d.name):
        md = skill_dir / "SKILL.md"
        if not skill_dir.is_dir() or not md.exists():
            continue
        text = md.read_text()
        if "[CLI-only]" in text and not args.all:
            skipped.append(skill_dir.name)
            continue

        files = [md] + sorted(p for p in skill_dir.rglob("*") if p.is_file() and p != md)
        zip_path = DIST / f"{skill_dir.name}.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
            for p in files:
                z.write(p, pathlib.Path(skill_dir.name) / p.relative_to(skill_dir))

        # Context cost is SKILL.md alone. Bundled references and programs sit on disk and
        # are read on demand by code execution, so counting them here would condemn
        # exactly the skills worth shipping: the ones that carry a program.
        tokens = est_tokens(len(text))
        payload = zip_path.stat().st_size
        if tokens > TOKEN_GUIDANCE:
            fat.append((skill_dir.name, tokens))
        packaged += 1
        extra = f"  + {payload // 1024}KB bundled" if len(files) > 1 else ""
        rows.append((skill_dir.name, tokens, payload // 1024 if len(files) > 1 else 0,
                     first_sentence(text)))
        print(f"  {skill_dir.name:<22} ~{tokens:>5} tokens{extra}")

    write_index(rows)
    print(f"\n{packaged} zip(s) in {DIST.relative_to(PLUGIN)}, with INDEX.md")
    print("Token figures are SKILL.md only, which is what loads into the conversation.")
    if skipped:
        print(f"skipped {len(skipped)} CLI-only: {', '.join(skipped)}")
    if fat:
        print(f"\nSKILL.md over claude.ai's ~{TOKEN_GUIDANCE} token guidance, trim before uploading:")
        for name, t in fat:
            print(f"  {name}: ~{t}")
    print("\nUpload at claude.ai -> Settings -> Capabilities -> Upload skill (one zip each).")
    print("Then enable each one from the Skills menu inside a conversation; they are off by default.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
